CREATE TABLE comments (
  id        VARCHAR(255) NOT NULL PRIMARY KEY,
  userId    VARCHAR(255) NOT NULL,
  postId    VARCHAR(255) NOT NULL,
  comment   VARCHAR(255) NOT NULL,
  postedAt  INTEGER NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES users(id),
  FOREIGN KEY (postId) REFERENCES posts(id)
);

CREATE TABLE likes (
  userId    VARCHAR(255) NOT NULL,
  postId    VARCHAR(255) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES users(id),
  FOREIGN KEY (postId) REFERENCES posts(id),
  PRIMARY KEY (userId, postId)
);